### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by Atman-7** [AmyangXYZ/AetherGazer_Vue#1]
你好, 想问一下,这个在哪个编译器进行打开,以及配置环境

**Comment by AmyangXYZ** [comment]
vscode + typescript + vue.js. 
`npm i` 安装依赖，`npm run dev`运行

**Comment by Atman-7** [comment]
> VSCode + 打字稿 + vue.js。 安装依赖，运行`npm i``npm run dev`

好的,感谢
